export const MISSING_CHARACTER =
  "https://potterdb.com/images/missing_character.svg";

export const CHARACTERS_PAGE_LIMIT = 20;

export const HOUSES = [
  "Gryffindor",
  "Slytherin",
  "Hufflepuff",
  "Ravenclaw",
  "Unknown",
  "Gryffindor, Hufflepuff, or Ravenclaw",
  "Slytherin (possibly)",
  "Gryffindor, Hufflepuff, or Slytherin",
  "Slytherin (formerly)",
  "Hufflepuff (possibly)",
  "Thunderbird",
  "Gryffindor (possibly)",
  "Pub landlady",
  "Did not attend Hogwarts",
  "Hufflepuff, Ravenclaw or Slytherin",
  "Ravenclaw or Slytherin",
  "Hogwarts kitchens employee",
  "Horned Serpent",
  "Ravenclaw or Hufflepuff",
  "Ravenclaw (possibly)",
  "Slytherin (most likely)",
  "Ravenclaw, Slytherin or Hufflepuff",
  "Ravenclaw (likely)",
  "Hufflepuff (likely)",
  "Slytherin (likely)",
  "Gryffindor (likely)",
  "Hogwarts School of Witchcraft and Wizardry",
  "Pukwudgie",
  "Hufflepuff or Ravenclaw",
  "Gryffindor, Hufflepuff or Slytherin",
  "Gryffindor, Hufflepuff or Ravenclaw",
  "Gryffindor or Slytherin",
  "Hufflepuff or Slytherin",
  "Wampus",
];

export const SPECIES = [
  "Human",
  "Human (werewolf)",
  "Abraxan",
  "Spider",
  "Peacock",
  "Phoenix",
  "Ferret",
  "Owl",
  "Niffler",
  "Goblin",
  "Vampire",
  "Humans",
  "Human, Ghost (possibly)",
  "Human (formerly), Ghost",
  "Hag",
  "Dragon",
  "Antipodean Opaleye",
  "Chupacabra",
  "Half-human/half-Veela",
  "Veela",
  "Common Welsh Green",
  "Acromantula",
  "Human (Obscurial)",
  "Pygmy Puff",
  "Eagle owl",
  "Deity",
  "Ashwinder",
  "Human, Worm (briefly)",
  "Augurey",
  "Dragon (Chinese Fireball)",
  "Human, Badger",
  "Ghost (formerly human)",
  "Hebridean Black",
  "Centaur",
  "Human (formerly), Inferius",
  "Kneazle",
  "Fruit bat",
  "Rabbit",
  "Billywig",
  "House-elf",
  "Birds",
  "Ghoul",
  "Boa constrictor",
  "Banshee",
  "Albino bloodhound",
  "Wolf (offspring of two transformed werewolves)",
  "Mooncalf",
  "Bowtruckle",
  "Giant",
  "Snowy owl",
  "Hippogriff",
  "Budgerigar",
  "Hungarian Horntail",
  "Pony",
  "Quintaped",
  "Human, Quintaped (Possibly)",
  "Part-human/one-eighth-Veela",
  "Human or part-human/quarter-Veela",
  "Cat",
  "Chimaera",
  "Chinese Fireball",
  "Clabbert",
  "Sphinxes",
  "Half-Kneazle cat",
  "House-Elf",
  "Unknown (mythical or possible non-being)",
  "Deer",
  "Veela or part-human/part-Veela",
  "Toad",
  "Part-human (one-eighth-Veela)",
  "Demiguise",
  "Doxy",
  "Human, Ferret (briefly)",
  "Parrot",
  "Tortoise",
  "Dugbog",
  "Human or half-breed",
  "Nundu",
  "Ghost (formerly Human)",
  "Great grey owl",
  "Fairy",
  "Boarhound",
  "Poltergeist",
  "Ghost, Human (formerly)",
  "Human (Werewolf)",
  "Frog",
  "Part-human/part-goblin",
  "Fire Dwelling Salamander",
  "Part-human (quarter-Veela)",
  "Three-headed dog",
  "Mooncalves",
  "Forest troll",
  "Human, Part-troll (possibly)",
  "Fox",
  "Fish (previously lily petal)",
  "Thunderbird",
  "Part-human/quarter-Veela",
  "Qilin",
  "Puffskein",
  "Giant Dung Beetle",
  "Rat",
  "Dog",
  "Snake (with characteristics of dragons and Basilisks)",
  "Humans (formerly), Ghosts",
  "Glow Bug",
  "Gnome",
  "Goblins",
  "Gorilla",
  "Dogs",
  "Graphorn",
  "Griffin",
  "Grindylows",
  "Dragon (Ukrainian Ironbelly)",
  "Giants",
  "Diricawl",
  "Unicorn",
  "Screech owl",
  "Basilisk",
  "Snakes",
  "Murtlap",
  "Fire Crab",
  "Hodag",
  "Giant Squid",
  "House-elves",
  "Mice",
  "Hummingbird",
  "Imp",
  "Half-elf/half-human",
  "Iguana",
  "Crup",
  "Human, Deity (in Christian belief)",
  "Zouwu",
  "Knarl",
  "Kelpie",
  "Tarantula",
  "Leucrotta",
  "Part-human/part-vampire",
  "Either Long-Haired Lurcher or Irish Wolfhound",
  "Manticore",
  "Matagot",
  "Goat",
  "Selkie (Merpeople)",
  "Human, Flobberworm (briefly), Puffskein (briefly)",
  "Hornbill, Water goblet (briefly)",
  "Human (formerly), Haddock",
  "Beastly Human (possibly), Creature (possibly)",
  "Snake",
  "Adder",
  "Mountain Troll",
  "Part-Kneazle cat",
  "Selkie",
  "Pixies",
  "Swooping Evil",
  "Human (Maledictus affliction; originally), Snake",
  "Newt",
  "Erumpent",
  "Runespoor",
  "Wyvern",
  "Troll",
  "Homo amphibia (purportedly)",
  "Norwegian Ridgeback",
  "Donkey",
  "Half-human/half-giant",
  "Human or giant",
  "Human or giantess",
  "Monkey",
  "Hippopotamus",
  "Elephant",
  "Tiger",
  "Wolfhound",
  "Scops owl",
  "Giraffe",
  "Mermaid",
  "Part-human/part-giant",
  "Half-vampire/half-human",
  "Goblin, Ghost",
  "Ginger Cat",
  "Red Cap",
  "Human (originally), Werewolf",
  "Grindylow",
  "Dog (breed: bulldog)",
  "Crups",
  "Dogs (pugs)",
  "Flobberworms",
  "Occamy",
  "Porlock",
  "Hound",
  "Dog (puggle)",
  "Sea serpent",
  "Thestral",
  "Black Cat",
  "Nifflers",
  "Human (transfigured to chicken)",
  "Barn owl",
  "Sphinx",
  "Snowy Owl",
  "Humans, One werewolf",
  "Wolf",
  "Thornback",
  "Yeti",
  "Animal ghost",
  "Humans (formerly), Hedgehogs",
  "Wampus cat",
  "Red Caps",
  "Mountain troll",
  "Bluebird",
  "Unknown",
  "Dragon (Antipodean Opaleye)",
  "Dragon (Swedish Short-Snout)",
  "Horse (formerly), Ghost horse",
  "Tawny owl",
  "Merperson",
  "Raven",
  "Ukrainian Ironbelly",
  "Winged horse",
  "Bulldogs",
  "Goblin or house-elf",
  "Giant Fire Crab",
  "Human (formerly), Vampire",
  "Ogre (possibly)",
  "Vampire, Part-vampire, or Human",
  "Chickens",
  "Ducks",
  "Pigs",
  "Pukwudgie",
  "Human (werewolf traits)",
];

export const BLOOD_STATUSES = [
  "Muggle",
  "Half-blood",
  "Pure-blood or half-blood",
  "Pure-blood, Half-blood, or Muggle-born",
  "Pure-blood",
  "Pure-blood, Half-blood or Squib (possibly)",
  "No-Maj",
  "Muggle-born (as determined by the Muggle-Born Registration Commission), Half-blood (claimed)",
  "Muggle-born or half-blood",
  "Half-blood or Squib",
  "Pure-blood or Half-blood (possibly)",
  "Pure-blood or half-blood (possibly)",
  "Pure-blood or half-blood (likely)",
  "Pure-blood or Half-blood",
  "Pure-blood, half-blood or Muggle-born",
  "Squib",
  "Muggle-born (possibly)",
  "Squib (possibly)",
  "Muggle-born",
  "Half-breed (half-Veela)",
  "Squib or wizard (likely)",
  "One or both of them magical",
  "Pure-bloods",
  "Half-blood or Muggle-born",
  "Pure-blood (most likely)",
  "Pure-blood or half-blood (presumably)",
  "Pure-blood (likely)",
  "Magical to unknown extent",
  "Pure-blood or half-blood (most likely)",
  "Half-blood (most likely)",
  "Pure-blood (possibly)",
  "Pure-blood, half-blood or Squib",
  "Half-breed (one-eighth-Veela)",
  "Half-breed (quarter-Veela) (possibly)",
  "Pure-blood (probably)",
  "Pure-blood, half-blood or Muggle-born (most likely)",
  "Half-bloods or Squibs",
  "No-Maj (most likely)",
  "Muggles",
  "Half-breed (part-human/part-Veela) (possibly)",
  "Half-breed (one-eighth Veela)",
  "Pure-bloods, half-bloods or Squibs",
  "Pure-blood (claimed) or half-breed (possibly, unproven)",
  "Pure-blood or Half-blood (most likely)",
  "Half-breed (part-goblin)",
  "Half-breed (quarter-Veela)",
  "Pure-Blood or Half-Blood",
  "Squibs",
  "Half-blood or Pure-blood",
  "Giant",
  "Pure-bloods or half-bloods",
  "Pure-blood, half-blood, and/or squib",
  "Half-breed (half-elf)",
  "Pure Blood,Half-Blood or Muggle-born",
  "Pure-blood or half-blood, or Squib",
  "Squib (suspected)",
  "No-Maj-born",
  "Muggle-born or Half-blood (possibly)",
  "Half-breed (part-vampire)",
  "Pure-blood, half-blood, or Squib",
  "Muggle-born or half-blood (possibly)",
  "No-Maj or Squib",
  "Muggle-born or half-blood (presumably)",
  "Half-blood or pure-blood (possibly)",
  "Half-blood, Pure-blood or Squib",
  "No-Maj (presumably)",
  "Underbeing",
  "Half-blood or Muggle-born (most likely)",
  "Muggle (implied)",
  "Half-breed (half-giant)",
  "Half-blood or pure-blood",
  "Muggle-born or half-blood (likely)",
  "Half-breed (part-giant)",
  "Half-breed (half-vampire)",
  "Pure blood or half-blood",
  "Pure-blood (self-proclaimed)",
  "Magical to some extent",
  "Muggle (most likely)",
  "Pure-blood, half-blood or Squib (most likely)",
  "Non-Magique",
  "Pure-blood or half-Blood",
  "Pure-bloods or Half-bloods",
  "Pure-blood, Half-blood, Muggle-born or Muggle",
  "Pure-blood, Half-blood or Squib",
  "Pure-blood(s) or/and half-blood(s)",
  "Muggle-borns",
  "Pure-Blood",
  "Muggle (as implied by the Muggle-Born Registration Commission), Pure-blood or half-blood (as claimed by his alleged son)",
  "Muggle (possibly)",
];

export const FILTERING_OPTIONS = ["name", "house", "blood_status", "species"];
